title: PhD Javier Izquierdo
description: Javier Izquierdo PhD blog
theme: just-the-docs
color_scheme: dark

url: https://roboticslaburjc.github.io/2026-phd-javier-izquierdo
repository: RoboticsLabURJC/2026-phd-javier-izquierdo
permalink: pretty

aux_links:
  Github Repository: https://github.com/RoboticsLabURJC/2026-phd-javier-izquierdo

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap