title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://roboticslaburjc.github.io/2026-phd-javier-izquierdo

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template